# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: About
  - name: About the Outfitter
    parent: About
    url: '/about/'
    weight: 20
  - name: Contact
    parent: About
    url: '/about/#contact'
  - name: Our Rivers
    parent: About
    url: '/our-rivers/'
  - name: Gear We Love
    parent: About
    url: '/gear-we-love/'