# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: Coffee
  theme_night: 
  font: minimal
  font_size: xl

# SEO

marketing:
  seo:
    site_type: LocalBusiness
    local_business_type: 'ProfessionalService'
    org_name: Montana Trout Hunters
    description: Montana's premier fly fishing outfitter experience.
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true
  image:
    height: 70
    width: 133

footer:
  copyright:
    notice: '© {year} Montana Trout Hunters. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/shoginn/montanatrouthunters.com'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

extensions:
  academicons:
    enable: false

i_am_a_sponsor: true

power_ups:
  hide_generator: true
