site:
  name: Montana Trout Hunters
  site: 'https://montanatrouthunters.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: ''

# Default SEO metadata
metadata:
  title:
    default: Montana Trout Hunters
    template: '%s — Montana Trout Hunters'
  description: "Montana's premier fly fishing outfitter experience."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Montana Trout Hunters
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: ''

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: 'G-XHCFKXDL1G' # or "G-XXXXXXXXXX"

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
